// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Home                 *LLACoords     `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	Locators             *LocatorConfig `protobuf:"bytes,2,opt,name=locators,proto3" json:"locators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_869785302f3ce625, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetHome() *LLACoords {
	if m != nil {
		return m.Home
	}
	return nil
}

func (m *Config) GetLocators() *LocatorConfig {
	if m != nil {
		return m.Locators
	}
	return nil
}

type LLACoords struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             float32  `protobuf:"fixed32,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LLACoords) Reset()         { *m = LLACoords{} }
func (m *LLACoords) String() string { return proto.CompactTextString(m) }
func (*LLACoords) ProtoMessage()    {}
func (*LLACoords) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_869785302f3ce625, []int{1}
}
func (m *LLACoords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LLACoords.Unmarshal(m, b)
}
func (m *LLACoords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LLACoords.Marshal(b, m, deterministic)
}
func (dst *LLACoords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LLACoords.Merge(dst, src)
}
func (m *LLACoords) XXX_Size() int {
	return xxx_messageInfo_LLACoords.Size(m)
}
func (m *LLACoords) XXX_DiscardUnknown() {
	xxx_messageInfo_LLACoords.DiscardUnknown(m)
}

var xxx_messageInfo_LLACoords proto.InternalMessageInfo

func (m *LLACoords) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LLACoords) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *LLACoords) GetAltitude() float32 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

type LocatorConfig struct {
	Deliveroo            *DeliverooConfig `protobuf:"bytes,1,opt,name=deliveroo,proto3" json:"deliveroo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LocatorConfig) Reset()         { *m = LocatorConfig{} }
func (m *LocatorConfig) String() string { return proto.CompactTextString(m) }
func (*LocatorConfig) ProtoMessage()    {}
func (*LocatorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_869785302f3ce625, []int{2}
}
func (m *LocatorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocatorConfig.Unmarshal(m, b)
}
func (m *LocatorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocatorConfig.Marshal(b, m, deterministic)
}
func (dst *LocatorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocatorConfig.Merge(dst, src)
}
func (m *LocatorConfig) XXX_Size() int {
	return xxx_messageInfo_LocatorConfig.Size(m)
}
func (m *LocatorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LocatorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LocatorConfig proto.InternalMessageInfo

func (m *LocatorConfig) GetDeliveroo() *DeliverooConfig {
	if m != nil {
		return m.Deliveroo
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "Config")
	proto.RegisterType((*LLACoords)(nil), "LLACoords")
	proto.RegisterType((*LocatorConfig)(nil), "LocatorConfig")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_869785302f3ce625) }

var fileDescriptor_config_869785302f3ce625 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x4f, 0x49, 0xcd, 0xc9, 0x2c, 0x4b,
	0x2d, 0xca, 0xcf, 0x87, 0x08, 0x28, 0x85, 0x70, 0xb1, 0x39, 0x83, 0x15, 0x08, 0xc9, 0x71, 0xb1,
	0x64, 0xe4, 0xe7, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x71, 0xe9, 0xf9, 0xf8, 0x38,
	0x3a, 0xe7, 0xe7, 0x17, 0xa5, 0x14, 0x07, 0x81, 0xc5, 0x85, 0xb4, 0xb8, 0x38, 0x72, 0xf2, 0x93,
	0x13, 0x4b, 0xf2, 0x8b, 0x8a, 0x25, 0x98, 0xc0, 0x6a, 0xf8, 0xf4, 0x7c, 0x20, 0x02, 0x10, 0x13,
	0x82, 0xe0, 0xf2, 0x4a, 0x89, 0x5c, 0x9c, 0x70, 0xed, 0x42, 0x52, 0x5c, 0x1c, 0x39, 0x89, 0x25,
	0x99, 0x25, 0xa5, 0x29, 0x10, 0xc3, 0x99, 0x82, 0xe0, 0x7c, 0x21, 0x19, 0x2e, 0xce, 0x9c, 0xfc,
	0xbc, 0x74, 0x88, 0x24, 0x13, 0x58, 0x12, 0x21, 0x00, 0xd2, 0x99, 0x98, 0x03, 0xd5, 0xc9, 0x0c,
	0xd1, 0x09, 0xe3, 0x2b, 0xd9, 0x73, 0xf1, 0xa2, 0xd8, 0x2e, 0xa4, 0xc7, 0xc5, 0x09, 0xf7, 0x1c,
	0xd4, 0x13, 0x02, 0x7a, 0x2e, 0x30, 0x11, 0xa8, 0x13, 0x11, 0x4a, 0x9c, 0x58, 0xa2, 0x98, 0x0a,
	0x92, 0x92, 0xd8, 0xc0, 0xc1, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x55, 0x6b, 0xf2, 0xc0,
	0x27, 0x01, 0x00, 0x00,
}
