// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deliveroo.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeliverooConfig struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliverooConfig) Reset()         { *m = DeliverooConfig{} }
func (m *DeliverooConfig) String() string { return proto.CompactTextString(m) }
func (*DeliverooConfig) ProtoMessage()    {}
func (*DeliverooConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_deliveroo_f6aeee11afc53c26, []int{0}
}
func (m *DeliverooConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverooConfig.Unmarshal(m, b)
}
func (m *DeliverooConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverooConfig.Marshal(b, m, deterministic)
}
func (dst *DeliverooConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverooConfig.Merge(dst, src)
}
func (m *DeliverooConfig) XXX_Size() int {
	return xxx_messageInfo_DeliverooConfig.Size(m)
}
func (m *DeliverooConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverooConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverooConfig proto.InternalMessageInfo

func (m *DeliverooConfig) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *DeliverooConfig) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*DeliverooConfig)(nil), "DeliverooConfig")
}

func init() { proto.RegisterFile("deliveroo.proto", fileDescriptor_deliveroo_f6aeee11afc53c26) }

var fileDescriptor_deliveroo_f6aeee11afc53c26 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x49, 0xcd, 0xc9,
	0x2c, 0x4b, 0x2d, 0xca, 0xcf, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a, 0xe4, 0xe2, 0x77,
	0x81, 0x09, 0x39, 0xe7, 0xe7, 0xa5, 0x65, 0xa6, 0x0b, 0x29, 0x73, 0xf1, 0x16, 0xa5, 0xa6, 0x15,
	0xa5, 0x16, 0x67, 0xc4, 0x97, 0xe4, 0x67, 0xa7, 0xe6, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0xf1, 0x40, 0x05, 0x43, 0x40, 0x62, 0x42, 0x8a, 0x5c, 0x3c, 0x89, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5,
	0x50, 0x35, 0x4c, 0x60, 0x35, 0xdc, 0x10, 0x31, 0xb0, 0x12, 0x27, 0x96, 0x28, 0xa6, 0x82, 0xa4,
	0x24, 0x36, 0xb0, 0x3d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0x13, 0xdb, 0x30, 0x7a,
	0x00, 0x00, 0x00,
}
