name: Bump Version

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Identify version bumps and tag the repo
        uses: deliveroo/label-semver-tagger.action@v1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          bump-script: versionFile
          bump-label-format: ${bumpType}
          tag-format: v${version}
